### ISSUE TITLE
Add stylua config for consistent code styling

### ISSUE THREAD

**Issue by body-clock** [adam12/ruby-lsp.nvim#16]
While working on a healthcheck, I noticed that my formatter was conflicting with the default code styling. Adding a default `.stylual.toml` to the base of the repo is a good way to ensure styling consistency. It's a pattern I've seen in most other plugins as well.

[This](https://github.com/nvim-lua/kickstart.nvim/blob/master/.stylua.toml) is a good starting point:
```toml
column_width = 160
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "None"
```

Perhaps we go with this default config? Maybe remove the `call_parentheses` option to enforce consistent parentheses usage?
